version: '2.1'
networks:
  common:
    driver: bridge

services:
  clickhouse_1:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse.cloki.deploy
    hostname: clickhouse.cloki.deploy
    domainname: clickhouse.cloki.deploy
    restart: unless-stopped
    networks:
      common:
        aliases:
          - "clickhouse_1"
    expose:
      - "9000"
      - "2181"
      - "9444"
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
  clickhouse_2:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse2.cloki.deploy
    hostname: clickhouse2.cloki.deploy
    domainname: clickhouse2.cloki.deploy
    restart: unless-stopped
    networks:
      common:
        aliases:
          - "clickhouse_2"
    expose:
      - "9000"
      - "2181"
      - "9444"
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
