name: pull view action
runs:
  using: "composite"
  steps:
    - run: |
        pwd && mkdir -p view && cd view && \
        wget https://github.com/metrico/qryn-view/releases/download/$TAG/dist.zip && \
        unzip -o dist.zip && rm dist.zip
      shell: bash
