name: Reusable Workflow

on:
  workflow_call:
    inputs:
      tag:
        type: string

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir view && cd view
      - run: wget https://github.com/metrico/qryn-view/releases/download/$TAG/dist.zip
        env:
          TAG: ${{ inputs.tag }}
      - run: unzip dist.zip && rm dist.zip
