# This workflow will validate qryn using nodejs + clickhouse

name: QRYN CI

on:
  push:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  workflow_dispatch:
    inputs:
      clickhouse_tag:
        description: 'Tag for ClickHouse (23.8-alpine)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    services:
      clickhouse:
        image: "clickhouse/clickhouse-server:${{ github.event.inputs.clickhouse_tag || '23.8-alpine' }}"
        ports:
          - 8123:8123
          - 9000:9000
    steps:
    - uses: actions/checkout@v4
    - name: build qryn-view
      uses: ./.github/actions/get-view
      env:
        TAG: v3.3.2
    - name: check if qryn-view pulled
      run: pushd view && ls | grep assets && popd
    - run: git submodule init
    - run: git submodule update
    - name: Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1.8.7
      if: github.event_name != 'pull_request'
    - env:
        NODE_VERSION: ${{ matrix.node-version }}
      run: "sh ./test/e2e/compose/clickhouse_sso_e2e/run_test.sh"
