# This workflow will validate qryn using nodejs + clickhouse

name: QRYN CI CLUSTER

on:
  push:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [ master, beta ]
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
  workflow_dispatch:
    inputs:
      clickhouse_tag:
        description: 'Tag for ClickHouse (23.8-alpine)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 16, 20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run postinstall
    - run: git submodule init
    - run: git submodule update
    - name: Install Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.1.0 # defaults to 'latest'
        legacy: true    # will also install in PATH as `docker-compose`
    - name: Workflow Telemetry
      uses: runforesight/workflow-telemetry-action@v1.8.7 
      if: github.event_name != 'pull_request'
    - env:
        NODE_VERSION: ${{ matrix.node-version }}
      run: "sh ./test/e2e/compose/clickhouse_cluster_e2e/run_test.sh"
